name: My First GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.8, 3.9]
      labels:
      - self-hosted
      - Linux
      - X64
      - label-1
      - label-2


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          cd src
          python -m pytest addition.py
